package com.ledger.system.enums;

public enum ErrorCode {

    INVALID_AMOUNT,
    INVALID_FEE,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_INVALID,
    INVALID_TRANSFER,
    INVALID_REFUND,
    TRANSACTION_NOT_FOUND,
    LEDGER_UNBALANCED,
    DUPLICATE_TRANSACTION,
    DUPLICATE_REFUND,
    DUPLICATE_TRANSFER,
    DUPLICATE_SETTELMENT
}
