apiVersion: apps/v1
kind: Deployment

metadata:
  name: ledger-core-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ledger-core-system

  template:
    metadata:
      labels:
        app: ledger-core-system

    spec:
      containers:
        - name: ledger-core-container

          image: assadburiro30/docker-jenkins-ledger-system-integrations:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: SERVER_PORT
              value: "8081"