CREATE TABLE idempotency_keys (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      key_value VARCHAR(255) NOT NULL UNIQUE,
      transaction_reference UUID,
      response JSON,
      status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
